// node modules
import Head from 'next/head';
import { useSelector } from 'react-redux';

// local files
import {
  Collections,
  Gender,
  Media,
  Categories,
  Products,
  Custom,
} from '../sections';
import useDetectMobileScreenSize from '../hooks/useDetectMobileScreenSize';
import { selectApp } from '../redux/slices/appSlice';
import { storyblokApi } from '../services/storyblok';

export default function Home({ story }: any) {
  // redux
  const { isMobileScreenSize } = useSelector(selectApp);

  // hooks
  useDetectMobileScreenSize();

  return (
    <div>
      <Head>
        <title>Venum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Media />
        {isMobileScreenSize && <Categories />}
        <Collections />
        <Gender />
        {!isMobileScreenSize && <Categories />}
        <Products />
        <Custom />
      </main>
    </div>
  );
}

export async function getStaticProps({ preview = false }) {
  const slug = 'home';
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, {
    version: 'draft',
  });

  return {
    props: {
      story: data ? data.story : false,
      preview,
    },
    revalidate: 3600, // revalidate every hour
  };
}
