// node modules
import Head from 'next/head';

// local files
import {
  Collections,
  Gender,
  Media,
  Categories,
  Products,
  Custom,
} from '../sections';
import useDetectMobileScreenSize from '../hooks/useDetectMobileScreenSize';

export default function Home() {
  // hooks
  useDetectMobileScreenSize();

  return (
    <div>
      <Head>
        <title>Venum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Media />
        <Collections />
        <Gender />
        <Categories />
        <Products />
        <Custom />
      </main>
    </div>
  );
}
